apiVersion: v1
kind: Service
metadata:
  name: status-page-api
  namespace: status-page
  labels:
    app: status-page-api
spec:
  type: ClusterIP
  selector:
    app: status-page-api
  ports:
    - name: http
      port: 80
      targetPort: http
